### ISSUE TITLE
Move to jump-dev

### ISSUE THREAD

**Issue by odow** [blegat/CDCS.jl#13]
@blegat why is this in `oxfordcontrol`? 

It seems like the only people to contribute are you and Joaquim: https://github.com/oxfordcontrol/CDCS.jl/graphs/contributors

**Comment by goulart-paul** [comment]
I think we just agreed to maintain it (or at least host it) since it's a wrapper for CDCS and it seemed reasonable for them to live together.

**Comment by odow** [comment]
If you're happy to have it here then great. I can close this. Just wondering since it's a bit of an outlier when I went to add it to the documentation: https://github.com/jump-dev/JuMP.jl/pull/3372
