### ISSUE TITLE
Old version of MATLAB.jl in Project.toml enforced downgrading

### ISSUE THREAD

**Issue by hurak** [blegat/CDCS.jl#6]
When `add`ing this package, my local `MATLAB.jl` package gets downgraded. The latest version released on Github is 0.8.2, while the version fixed in CDCS's Project.toml is 0.7.3.

I still do not fully get how this versioning works in Julia. But I guess that in this case the CDCS.jl package is the blocker, isn't it? Would it be possible to relax the restriction to the now old 0.7.x versions of MATLAB.jl?

**Comment by blegat** [comment]
Closed by https://github.com/oxfordcontrol/CDCS.jl/pull/7
